# -*- coding: utf-8 -*-
"""Practical 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbaXm_HkKJ0d0I3fBsKNLleFXZH_CvqZ
"""

#Name: Ankur Dome
#Roll No: 508
#PRN: 202201040191


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/tips.csv")
print(df)
g1 = df['day'].value_counts()
print(g1)
print()
plt.xlabel("Days")
plt.ylabel("Number of people")
plt.title("Day preference of people to visit Restraunt")
plt.scatter(g1.index,g1, c="magenta")

g2 = df.groupby('day')['tip'].mean()
plt.bar(g2.index,g2)
plt.xlabel("Day")
plt.ylabel("Average Tip")
plt.title("Average Tip by Day")
plt.show()

g3 = df["sex"].value_counts()
mylabels = ["Male", "Female"]
plt.pie(g3, labels = mylabels)
plt.title("Proportion of Male vs Female going Restraunt")
plt.show()

df["total_bill"] = df['total_bill'].astype('int32')
g4 = df.groupby("total_bill")["tip"].mean()
plt.xlabel("Total Bill")
plt.ylabel("Tip Given")
plt.title("Average Tip Given on Bill")
plt.scatter(g4.index, g4, color="#88c999")
plt.show()

g5 = df.groupby("day")["tip"].mean()
plt.xlabel("Day")
plt.ylabel("Tip Got")
plt.title("Average Tip Given on Specific Days")
plt.barh(g5.index, g5, color = "red")

"""Day vs Total Bill (For Dinner/Lunch)"""

import seaborn as sns
sns.violinplot(data=df,x='day', y ='total_bill',hue='time')

"""Day vs Total Bill (For Male/Female)"""

sns.catplot(
    data=df, x="total_bill", y="day", hue="sex",
    kind="violin", bw=.15, cut=0,
)

"""Smoker vs Tip (as per smoking yes and no)"""

sns.catplot(data=df, x="smoker", y="tip", order=["No", "Yes"])

"""Total vs Day (as per Male/Female)"""

sns.catplot(data=df, x="day", y="total_bill", hue="sex", kind="swarm")

""".

.

.

Total Bill vs Day (as per smoking yes or no)
"""

sns.catplot(data=df, x="day", y="total_bill", hue="smoker", kind="box")