# -*- coding: utf-8 -*-
"""Practical 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MiA5wNg6jwobyt_qwjcrU2AevP56VK_U

# **Practica Assignment 2**
Prepare/Take dataset for any real life application. For Ex. Sales of the company. Read the data from
Sales.csv/.xls/.txt. Store Product details in List data structure. Store Supplier Details in Dictionary
Data Structure. Store Customer Details in Tuple Data Structure. Now perform the following operations:
- Find the most popular product for sales.
- Find the best supplier for sales.
- Find the customer who buys most of the products.
- Find the number of customer who are ‘Female’
"""

#Name: Ankur Dome
#Division: E
#Roll: 508

#Functions
def convert(listx):
  dictionaryx={}
  for i in range(0, len(listx),2):
    dictionaryx[listx[i]]= listx[i+1]
  return dictionaryx

def countx(countxx):
    count = 0
    for i in range(len(Gender)):
     if Gender[i]== "Female":
       count+=1
    return count

#Main Body
import statistics
import csv
file1 = open("/content/sales.csv","r")
data1 = list(csv.reader(file1))

Product_Details = []
for i in range(len(data1)):
  Product_Details.append(data1[i][1])
print(Product_Details)

Supplier_Details = []
for i in range(len(data1)):
  Supplier_Details.append(data1[i][0])
  Supplier_Details.append(data1[i][2])
print(convert(Supplier_Details))

CDL = []
for i in range(len(data1)):
  CDL.append(data1[i][3])
Customer_Details = tuple(CDL)
print(Customer_Details)

Gender = []
for i in range(len(data1)):
  Gender.append(data1[i][4])
print(Gender)

#Operations to be performed
print("The most popular product for sell:",statistics.mode(Product_Details))
print("The supplier with most sales & hence the best supplier:", statistics.mode(Supplier_Details))
print("The customer buying most products:",statistics.mode(Customer_Details))
print("Total Number of Female Customers are:", countx(count))
file1.close()